<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Div_Speaker</name>
   <tag></tag>
   <elementGuidId>9c389e49-499a-4a79-af52-8b626f37ab86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='speakersImg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='speakersImg']</value>
      <webElementGuid>ae590d95-2b87-437b-9b22-433deb573824</webElementGuid>
   </webElementProperties>
</WebElementEntity>
