<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_postal_code</name>
   <tag></tag>
   <elementGuidId>c1f554a1-c3fc-493b-bb30-bfaeb8291fb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[3]/div[3]/sec-view/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[3]/div[3]/sec-view/div/input</value>
      <webElementGuid>60c820c3-1145-4509-9229-88c45e9f83b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
