<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_first_last_name</name>
   <tag></tag>
   <elementGuidId>5dc77b9b-6c00-43c3-a0a7-886579fc0469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[2]/div[1]/sec-view[${field}]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[2]/div[1]/sec-view[${field}]/div/input</value>
      <webElementGuid>d43b691c-2351-470e-9cf4-2a896fa66b6b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
