<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_password_confirm_password</name>
   <tag></tag>
   <elementGuidId>9840afc3-1a67-4160-ac74-e79bebd5e5f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[1]/div[2]/sec-view[${field}]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[1]/div[2]/sec-view[${field}]/div/input</value>
      <webElementGuid>bec49149-c354-449e-b490-c3d6d69199d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
