<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_username_email</name>
   <tag></tag>
   <elementGuidId>efc68d21-84ed-436e-a140-d1cd2b90fe57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[1]/div[1]/sec-view[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[1]/div[1]/sec-view[${field}]/div/input</value>
      <webElementGuid>e3f3be2c-af41-4f9e-b24a-ec9fffed5502</webElementGuid>
   </webElementProperties>
</WebElementEntity>
